use_frameworks!

target 'RxCoreData_Example' do
  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'
  pod 'RxDataSources', '~> 1.0'
  pod 'RxCoreData', :path => '../'
end

target 'RxCoreData_Tests' do
    inherit! :search_paths
    pod 'RxCoreData', :path => '../'
end
