platform :"ios", "9.3"
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxCoreData_Example' do
  pod 'RxSwift', '~> 4.3.1'
  pod 'RxCocoa', '~> 4.3.1'
  pod 'RxDataSources', '~> 3.0'
  pod 'RxCoreData', :path => '../'
end

target 'RxCoreData_Tests' do
    inherit! :search_paths
    pod 'RxCoreData', :path => '../'
end
