use_frameworks!

target 'RxCoreData_Example' do
  pod 'RxSwift', '~> 3.0.0-rc.1'
  pod 'RxCocoa', '~> 3.0.0-rc.1'
  pod 'RxDataSources', '~> 1.0.0-rc.1'
  pod 'RxCoreData', :path => '../'
end

target 'RxCoreData_Tests' do
    inherit! :search_paths
    pod 'RxCoreData', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
