# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode9
before_install:
 - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
 - pod repo update --silent
 - pod install --project-directory=Example --repo-update
script:
- set -o pipefail && xcodebuild test -workspace Example/RxCoreData.xcworkspace -scheme RxCoreData-Example -configuration 'Debug' -sdk iphonesimulator -destination platform='iOS Simulator',OS='11.0',name='iPhone 8' build test  | xcpretty -c --test
- pod lib lint
